#!/usr/bin/env bash
# Coding Partner — Docker one-click install (no clone needed)
#
# Usage:
#   curl -fsSL <raw-url>/scripts/install-docker.sh | bash
#
set -euo pipefail

INSTALL_DIR="${CODING_PARTNER_DIR:-$HOME/coding-partner}"

# ── Colors ──────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()  { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
err()   { echo -e "${RED}[ERROR]${NC} $*"; }

# ── Banner ──────────────────────────────────────────────
echo ""
echo -e "${CYAN}╔══════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║   Coding Partner — Docker Install        ║${NC}"
echo -e "${CYAN}║   飞书 Vibe Coding 机器人                ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════╝${NC}"
echo ""

# ── 1. Check Docker ─────────────────────────────────────
MISSING=0

if command -v docker &>/dev/null; then
    ok "docker ✓"
else
    err "docker not found — install: https://docs.docker.com/get-docker/"
    MISSING=1
fi

COMPOSE_CMD=""
if docker compose version &>/dev/null 2>&1; then
    ok "docker compose ✓"
    COMPOSE_CMD="docker compose"
elif command -v docker-compose &>/dev/null; then
    ok "docker-compose ✓"
    COMPOSE_CMD="docker-compose"
else
    err "docker compose not found — install: https://docs.docker.com/compose/install/"
    MISSING=1
fi

if [ "$MISSING" -eq 1 ]; then
    echo ""
    err "Please install missing dependencies and re-run."
    exit 1
fi

echo ""

# ── 2. Create install directory ─────────────────────────
info "Install directory: $INSTALL_DIR"
mkdir -p "$INSTALL_DIR"

# ── 3. Write docker-compose.yml ─────────────────────────
# Docker natively supports building from a git URL
COMPOSE_FILE="$INSTALL_DIR/docker-compose.yml"

# Detect Claude CLI path on host
CLAUDE_BIN=""
CLAUDE_MOUNT=""
if command -v claude &>/dev/null; then
    CLAUDE_BIN="$(readlink -f "$(command -v claude)" 2>/dev/null || command -v claude)"
    ok "Detected host Claude CLI: $CLAUDE_BIN"
    CLAUDE_MOUNT="      - ${CLAUDE_BIN}:/usr/local/bin/claude:ro"
else
    warn "Claude CLI not found on host."
    warn "You will need to either:"
    warn "  1) Install Claude CLI and re-run this script, or"
    warn "  2) Uncomment the Claude install line in the Dockerfile"
    CLAUDE_MOUNT="      # - /path/to/claude:/usr/local/bin/claude:ro"
fi

# Detect Claude config directory
CLAUDE_CONFIG_MOUNT=""
if [ -d "$HOME/.claude" ]; then
    CLAUDE_CONFIG_MOUNT="      - ${HOME}/.claude:/root/.claude:ro"
else
    CLAUDE_CONFIG_MOUNT="      # - \${HOME}/.claude:/root/.claude:ro"
fi

cat > "$COMPOSE_FILE" << YAML
# Generated by coding-partner install-docker.sh
# To rebuild: $COMPOSE_CMD up -d --build
services:
  coding-partner:
    build: https://github.com/anthropics/coding-partner.git#main
    restart: unless-stopped
    env_file: .env
    volumes:
      # Mount host repos so Claude can access them
      - \${REPO_BASE_PATH:-~/code}:/repos
      # Persist SQLite database
      - ./data:/app/data
      # Claude CLI binary from host
${CLAUDE_MOUNT}
      # Claude config from host
${CLAUDE_CONFIG_MOUNT}
    environment:
      - REPO_BASE_PATH=/repos
      - DB_PATH=/app/data/coding_partner.db
YAML

ok "Written $COMPOSE_FILE"
echo ""

# ── 4. Interactive .env creation ────────────────────────
ENV_FILE="$INSTALL_DIR/.env"

if [ -f "$ENV_FILE" ]; then
    info "Existing .env found, keeping it."
    info "Edit $ENV_FILE to update configuration."
else
    info "Configure Feishu credentials:"
    echo ""

    read -rp "  FEISHU_APP_ID: " FEISHU_APP_ID
    read -rp "  FEISHU_APP_SECRET: " FEISHU_APP_SECRET
    read -rp "  BOT_OPEN_ID (optional): " BOT_OPEN_ID
    read -rp "  REPO_BASE_PATH [~/code]: " REPO_BASE_PATH
    REPO_BASE_PATH="${REPO_BASE_PATH:-~/code}"

    cat > "$ENV_FILE" << EOF
FEISHU_APP_ID=${FEISHU_APP_ID}
FEISHU_APP_SECRET=${FEISHU_APP_SECRET}
BOT_OPEN_ID=${BOT_OPEN_ID}
REPO_BASE_PATH=${REPO_BASE_PATH}
DB_PATH=/app/data/coding_partner.db
LOG_LEVEL=INFO
EOF

    ok "Config saved to $ENV_FILE"
fi

echo ""

# ── 5. Verify required values ──────────────────────────
source "$ENV_FILE"
if [ -z "${FEISHU_APP_ID:-}" ] || [ -z "${FEISHU_APP_SECRET:-}" ]; then
    warn "FEISHU_APP_ID or FEISHU_APP_SECRET is empty in .env"
    warn "Please edit $ENV_FILE before starting."
fi

# ── 6. Start ────────────────────────────────────────────
echo ""
read -rp "Start containers now? [Y/n] " START_ANSWER
START_ANSWER="${START_ANSWER:-y}"

if [[ "$START_ANSWER" =~ ^[Yy]$ ]]; then
    info "Building and starting..."
    cd "$INSTALL_DIR"
    $COMPOSE_CMD up -d --build
    echo ""
    ok "Containers started!"
else
    info "Skipped. To start manually:"
    echo "  cd $INSTALL_DIR && $COMPOSE_CMD up -d --build"
fi

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║   Install complete!                      ║${NC}"
echo -e "${GREEN}║   在飞书中找到机器人，发送 /repo 开始    ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════╝${NC}"
echo ""
echo "  Logs:    cd $INSTALL_DIR && $COMPOSE_CMD logs -f"
echo "  Stop:    cd $INSTALL_DIR && $COMPOSE_CMD down"
echo "  Config:  $ENV_FILE"
echo ""
